import { z } from 'zod';
import {
  toErrorResponse,
  toJsonResponse,
  type ToolContext,
  type ToolDefinition,
  type ToolResponse,
} from '../types.js';

// ---------- crear_grupo ----------

const CrearGrupoSchema = z
  .object({
    course_id: z.number().int().positive(),
    name: z.string().min(1).max(254),
    description: z.string().default(''),
    idnumber: z
      .string()
      .default('')
      .describe('Optional stable idnumber. Empty = auto-generated by Moodle.'),
  })
  .strict();

export type CrearGrupoInput = z.infer<typeof CrearGrupoSchema>;

export function buildCrearGrupoTool(): ToolDefinition<CrearGrupoInput> {
  return {
    name: 'crear_grupo',
    description:
      'Create a group inside a course. Use asignar_a_grupo to populate it after.',
    inputSchema: CrearGrupoSchema,
    handler: (args, ctx) => crearGrupo(args, ctx),
  };
}

export const crearGrupoTool = buildCrearGrupoTool();

async function crearGrupo(args: CrearGrupoInput, ctx: ToolContext): Promise<ToolResponse> {
  try {
    const created = (await ctx.client.call('core_group_create_groups', {
      groups: [
        {
          courseid: args.course_id,
          name: args.name,
          description: args.description,
          descriptionformat: 1,
          ...(args.idnumber !== '' && { idnumber: args.idnumber }),
        },
      ],
    })) as Array<{ id: number; name: string; idnumber?: string }> | undefined;

    if (!Array.isArray(created) || created.length === 0) {
      throw new Error('core_group_create_groups returned no group');
    }

    const g = created[0]!;
    return toJsonResponse({
      group_id: g.id,
      name: g.name,
      idnumber: g.idnumber ?? null,
      course_id: args.course_id,
    });
  } catch (e) {
    ctx.logger.warn('crear_grupo.failed', {
      course_id: args.course_id,
      error: (e as Error).message,
    });
    return toErrorResponse(e);
  }
}

// ---------- asignar_a_grupo ----------

const AsignarGrupoSchema = z
  .object({
    group_id: z.number().int().positive(),
    user_ids: z.array(z.number().int().positive()).min(1),
  })
  .strict();

export type AsignarAGrupoInput = z.infer<typeof AsignarGrupoSchema>;

export function buildAsignarAGrupoTool(): ToolDefinition<AsignarAGrupoInput> {
  return {
    name: 'asignar_a_grupo',
    description: 'Add one or more users to a group by group_id.',
    inputSchema: AsignarGrupoSchema,
    handler: (args, ctx) => asignar(args, ctx),
  };
}

export const asignarAGrupoTool = buildAsignarAGrupoTool();

async function asignar(args: AsignarAGrupoInput, ctx: ToolContext): Promise<ToolResponse> {
  try {
    await ctx.client.call('core_group_add_group_members', {
      members: args.user_ids.map((userid) => ({ groupid: args.group_id, userid })),
    });
    return toJsonResponse({
      group_id: args.group_id,
      added: args.user_ids.length,
      user_ids: args.user_ids,
    });
  } catch (e) {
    ctx.logger.warn('asignar_a_grupo.failed', {
      group_id: args.group_id,
      count: args.user_ids.length,
      error: (e as Error).message,
    });
    return toErrorResponse(e);
  }
}
