<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_italiciamcp_upsert_page' => [
        'classname'    => 'local_italiciamcp\\external\\upsert_page',
        'methodname'   => 'execute',
        'description'  => 'Create or update a mod_page in a course section, keyed by a stable idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_delete_module_by_idnumber' => [
        'classname'    => 'local_italiciamcp\\external\\delete_module_by_idnumber',
        'methodname'   => 'execute',
        'description'  => 'Delete a course module identified by its idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_update_course_summary' => [
        'classname'    => 'local_italiciamcp\\external\\update_course_summary',
        'methodname'   => 'execute',
        'description'  => 'Update the summary (description) of a course',
        'type'         => 'write',
        'capabilities' => 'moodle/course:update',
        'ajax'         => true,
    ],
    'local_italiciamcp_upsert_quiz' => [
        'classname'    => 'local_italiciamcp\\external\\upsert_quiz',
        'methodname'   => 'execute',
        'description'  => 'Create or update a mod_quiz shell (no questions), keyed by idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_upload_file' => [
        'classname'    => 'local_italiciamcp\\external\\upload_file',
        'methodname'   => 'execute',
        'description'  => 'Upload a base64-encoded file into the course media filearea. Returns pluginfile URL.',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_add_questions_gift' => [
        'classname'    => 'local_italiciamcp\\external\\add_questions_gift',
        'methodname'   => 'execute',
        'description'  => 'Parse GIFT text, create questions in a course bank category, append them to an existing quiz by idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities,moodle/question:add',
        'ajax'         => true,
    ],
    'local_italiciamcp_delete_module_by_cmid' => [
        'classname'    => 'local_italiciamcp\\external\\delete_module_by_cmid',
        'methodname'   => 'execute',
        'description'  => 'Delete a course_module by its cmid (use for modules without idnumber)',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_promote_quiz_questions' => [
        'classname'    => 'local_italiciamcp\\external\\promote_quiz_questions',
        'methodname'   => 'execute',
        'description'  => 'Promote all question_versions linked to a quiz from status=draft to status=ready',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_repair_quiz_sections' => [
        'classname'    => 'local_italiciamcp\\external\\repair_quiz_sections',
        'methodname'   => 'execute',
        'description'  => 'Ensure a quiz has a default quiz_sections row (firstslot=1)',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_upsert_url' => [
        'classname'    => 'local_italiciamcp\\external\\upsert_url',
        'methodname'   => 'execute',
        'description'  => 'Create or update a mod_url in a course section, keyed by a stable idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_upsert_assignment' => [
        'classname'    => 'local_italiciamcp\\external\\upsert_assignment',
        'methodname'   => 'execute',
        'description'  => 'Create or update a mod_assign in a course section, keyed by a stable idnumber',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_promote_all_drafts_in_course' => [
        'classname'    => 'local_italiciamcp\\external\\promote_all_drafts_in_course',
        'methodname'   => 'execute',
        'description'  => 'Promote every question_versions.status=draft to ready across all quizzes in a course (fixes the silent-edit bug in Moodle 4.5+/5.x)',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
    'local_italiciamcp_update_question_simple' => [
        'classname'    => 'local_italiciamcp\\external\\update_question_simple',
        'methodname'   => 'execute',
        'description'  => 'Direct DB update of question name / questiontext / answers, bypassing the Moodle edit form that fails silently in Moodle 5.0.2 qbank',
        'type'         => 'write',
        'capabilities' => 'moodle/course:manageactivities',
        'ajax'         => true,
    ],
];
